sudo: false
language: node_js
node_js:
  - "2"
  - "3"
  - "4"
  - "6"
  - "7"
  - "8"
script:
  - "npm run test-cov"
after_script:
  - "npm i codecov.io && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js"
